version: "3"
services:
    web:
        environment:
            VIRTUAL_HOST: ledit.marioslab.io
            LETSENCRYPT_HOST: ledit.marioslab.io
            LETSENCRYPT_EMAIL: badlogicgames@gmail.com
        networks:
            - reverse_proxy
    db:
        ports:
            - 5432:10000
networks:
    reverse_proxy:
        external:
            name: nginx-proxy
