version: "3"
volumes:
    db_data:
services:
    web:
        image: nginx:alpine
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ../html:/www
            - ./data/logs:/logs
        links:
            - server
        networks:
            - network

    server:
        build:
            context: .
            dockerfile: Dockerfile
        stop_grace_period: 2s
        environment:
            PORT: 3333
            DATABASE: ledit_db
            DATABASE_USER: ledit_db_user
            DATABASE_PASSWORD: ${LEDIT_DB_PASSWORD}
        volumes:
            - ./data:/data
            - ../:/app
        links:
            - db
        networks:
            - network
    db:
        image: postgres:16-alpine
        restart: always
        environment:
            POSTGRES_DB: ledit_db
            POSTGRES_USER: ledit_db_user
            POSTGRES_PASSWORD: ${LEDIT_DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - network

networks:
    network:
        driver: bridge
